const chatStyles = {
  chatPanel: {
    width: 260,
    display: "flex",
    flexDirection: "column",
    borderLeft: "1px solid #222",
    background: "#0d0d0d",
    flexShrink: 0,
  },
  chatHeader: {
    padding: "14px 16px",
    borderBottom: "1px solid #1e1e1e",
    fontSize: 11,
    color: "#555",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
  },
  chatMessages: {
    flex: 1,
    overflowY: "auto",
    padding: "12px 10px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    scrollbarWidth: "thin",
    scrollbarColor: "#222 transparent",
  },
  msgUser: {
    display: "flex",
    justifyContent: "flex-end",
  },
  msgBot: {
    display: "flex",
    justifyContent: "flex-start",
  },
  bubbleUser: {
    background: "#1a3a5c",
    color: "#a8d4ff",
    borderRadius: "12px 12px 2px 12px",
    padding: "8px 12px",
    fontSize: 12,
    maxWidth: "80%",
    lineHeight: 1.5,
  },
  bubbleBot: {
    background: "#1a1a1a",
    color: "#ccc",
    border: "1px solid #2a2a2a",
    borderRadius: "12px 12px 12px 2px",
    padding: "8px 12px",
    fontSize: 12,
    maxWidth: "80%",
    lineHeight: 1.5,
  },
  chatInputRow: {
    display: "flex",
    gap: 6,
    padding: "10px",
    borderTop: "1px solid #1e1e1e",
  },
  chatInput: {
    flex: 1,
    background: "#141414",
    border: "1px solid #2a2a2a",
    borderRadius: 6,
    color: "#ccc",
    padding: "8px 10px",
    fontSize: 12,
    outline: "none",
    fontFamily: "inherit",
  },
  sendBtn: {
    background: "#1a3a5c",
    border: "none",
    borderRadius: 6,
    color: "#3b82f6",
    padding: "0 12px",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    transition: "background 0.15s",
  },
};

export default chatStyles;