const sidebarStyles = {
  sidebar: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    padding: "12px 0",
    borderRight: "1px solid #222",
    background: "#0d0d0d",
    transition: "width 0.25s ease",
    flexShrink: 0,
    overflow: "hidden",
  },
  hamburger: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: "8px",
  },
  hamburgerLine: {
    display: "block",
    width: 18,
    height: 1.5,
    background: "#888",
    borderRadius: 2,
  },
  navItems: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    marginTop: 16,
  },
  navBtn: {
    background: "none",
    border: "none",
    color: "#555",
    fontSize: 10,
    cursor: "pointer",
    padding: "6px",
    borderRadius: 4,
    transition: "color 0.15s",
  },
  menuLabel: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: "#333",
    fontSize: 11,
    letterSpacing: "0.15em",
    textTransform: "uppercase",
  },
  profileBtn: {
    background: "none",
    border: "1px solid #222",
    color: "#666",
    borderRadius: "50%",
    width: 36,
    height: 36,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    marginBottom: 8,
    transition: "border-color 0.15s",
  },
};

export default sidebarStyles;